version: '3'

services:
  testdb:
    container_name: postgres_test_db
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=root
    ports:
      - 5444:5432